# Generated by Django 2.0 on 2018-02-25 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Basic_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=30)),
                ('travel_expenses', models.CharField(max_length=100)),
                ('hotel_expenses', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=100)),
                ('info', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='additional_data',
            name='information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Basic_data'),
        ),
    ]
