# Generated by Django 2.0 on 2018-02-26 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_data',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='basic_data',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
